extends Node

@warning_ignore("unused_signal")
signal player_damaged()
@warning_ignore("unused_signal")
signal player_regenerating()
@warning_ignore("unused_signal")
signal anim_hookable_finished()
@warning_ignore("unused_signal")
signal player_died()
@warning_ignore("unused_signal")
signal player_respawned()
@warning_ignore("unused_signal")
signal checkpoint_touched(point: Checkpoint)
@warning_ignore("unused_signal")
signal checkpoint_respawn(point: Checkpoint)
